[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
celo = "https://forno.celo.org"
alfajores = "https://alfajores-forno.celo-testnet.org"

[etherscan]
celo = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
